name: Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NODE_ENV: production
  GO_VERSION: "1.21.3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: |
            client/go.sum

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build API
        run: cd ./api && bun install && bun run build

      - name: Build Navigator
        run: cd ./navigator && bun install && bun run build

      - name: Build Client
        run: cd client && CGO_ENABLED=0 go build -a -installsuffix cgo -o ./dist/client ./src

      - name: Create .env
        run: |
          touch .env
          echo IP=${{ secrets.IP }} >> .env
          echo MULLVAD_COUNTRIES=${{ vars.MULLVAD_COUNTRIES }} >> .env
          echo OUTPUT_PATH=${{ vars.OUTPUT_PATH }} >> .env
          echo PUBLIC_URL=${{ vars.PUBLIC_URL }} >> .env
          echo WIREGUARD_ENABLED=${{ vars.WIREGUARD_ENABLED }} >> .env
          echo JELLYFIN_API_KEY=${{ secrets.JELLYFIN_API_KEY }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo MULLVAD_ACCOUNT=${{ secrets.MULLVAD_ACCOUNT }} >> .env
          echo "PRIV_KEY=${{ secrets.PRIV_KEY }}" >> .env
          echo "PUB_KEY=${{ secrets.PUB_KEY }}" >> .env

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts

      - name: Copy builds to server
        run: |
          ssh root@${{ secrets.IP }} "mkdir -p /root/freeflix && mkdir -p /root/freeflix/api && mkdir -p /root/freeflix/client && mkdir -p /root/freeflix/navigator"
          rsync -vrm ./navigator/dist/* root@${{ secrets.IP }}:/root/freeflix/navigator --delete
          ssh root@${{ secrets.IP }} "cd /root/freeflix && docker-compose down; exit 0"
          scp ./docker-compose.yml root@${{ secrets.IP }}:/root/freeflix/docker-compose.yml
          scp ./.env root@${{ secrets.IP }}:/root/freeflix/.env
          scp ./client/Dockerfile root@${{ secrets.IP }}:/root/freeflix/client/Dockerfile
          scp ./Caddyfile root@${{ secrets.IP }}:/root/freeflix/Caddyfile
          scp ./api/dist/api.js root@${{ secrets.IP }}:/root/freeflix/api/
          scp ./client/dist/client root@${{ secrets.IP }}:/root/freeflix/client/

      - name: Start server
        run: |
          ssh root@${{ secrets.IP }} "cd /root/freeflix && docker-compose up -d --build"
